### ISSUE TITLE
Readme file is not useful

### ISSUE THREAD

**Issue by philw764** [philw764/terraform-provider-servicenowcmdb#7]
Need to update the readme file to be more descriptive of the provider instead of talking about how to contribute

**Comment by demorphica** [comment]
hi @philw764 this is great 

please register your provider & add a valid terraform block to your readme so that others can test & contribute to it

```terraform {
  required_providers {
    servicenowcmdb = {
      source = "philw764/servicenowcmdb"
      version = ""
    }
  }
}```

a version would need to be specified else this error would block further testing

```
│ Error: Invalid version constraint
│
│   on main.tf line 5, in terraform:
│    5:       version = ""
│
│ This string does not use correct version constraint syntax.
╵

```

**Comment by demorphica** [comment]
https://github.com/philw764/terraform-provider-servicenowcmdb/issues/14
